services:    
  db-ponta:
    image: mariadb:latest
    container_name: db-ponta
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress-ponta
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    networks:
      - praia-net
    volumes:
      - db-client2_data:/var/lib/mysql

  wordpress-ponta:
    image: wordpress:latest
    container_name: wordpress-ponta
    depends_on:
      - db-ponta
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-ponta
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress-ponta
    networks:
      - praia-net
      - praia-net-proxy
    volumes:
      - wordpress-ponta_data:/var/www/html

  wordpress-ponta-2:
    image: wordpress:latest
    container_name: wordpress-ponta-2
    depends_on:
      - db-ponta
    restart: always
    tty: true
    environment:
      WORDPRESS_DB_HOST: db-ponta
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress-ponta
    networks:
      - praia-net
      - praia-net-proxy
    volumes:
      - wordpress-ponta_data:/var/www/html
  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh-ponta
    ports:
      - "4444:22"
    networks:
      - praia-net

volumes:
  db-client2_data:
  wordpress-ponta_data:

networks:
  praia-net:
    driver: bridge
  # Rede para comunicação com o proxy geral
  praia-net-proxy:
    external: true