services:    
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - praia-net
    volumes:
      - ./dns/conf/db.pipa.com:/etc/bind/db.pipa.com
      - ./dns/conf/named.conf.local:/etc/bind/named.conf.local
    
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dns
      - email
      - webmail
    networks:
      - praia-net
    volumes:
      - ./proxy/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/conf/ssl:/etc/nginx/ssl
  
  email:
    build:
      context: ./mail
      dockerfile: Dockerfile
    image: email
    container_name: email
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "110:110/tcp"
      - "143:143/tcp"
      - "465:465/tcp" # Adicione esta linha para permitir conexões seguras na porta 465
    networks:
      - praia-net
    volumes:
      - ./mail/conf/main.cf:/etc/postfix/main.cf
      - ./mail/conf/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./mail/conf/10-master.conf:/etc/dovecot/conf.d/10-master.conf
      - ./mail/data:/home
      - ./mail/ssl:/etc/dovecot/ssl

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: webmail
    networks:
      - praia-net
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://email:143
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://email:25
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    depends_on:
      - email
    volumes:
      - ./webmail/conf/config.inc.php:/var/roundcube/config/config.inc.php
      - ./mail/conf/ssl/email.crt:/etc/ssl/certs/email.crt:ro

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh
    ports:
      - "22:22"
    networks:
      - praia-net

networks:
  praia-net:
    driver: bridge
